### ISSUE TITLE
Launch code

### ISSUE THREAD

**Issue by victordalet** [Garenteeh/open_source#3]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Garenteeh** [comment]
Hello, 

Do 
```shell 
rails s 
```
in your git bash .

**Comment by victordalet** [comment]
Thanks

**Comment by Garenteeh** [comment]
probleme solve !
